version: '3.1'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3000:3000'

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db/db_data:/var/lib/postgresql/data
